# Libraries

In [93]:
import yfinance as yf
import pandas as pd

# Data Collection

In [94]:
spy_data=yf.download("SPY","2011-08-14","2026-08-13")
spy_data.to_csv("../data/raw.csv")

[*********************100%***********************]  1 of 1 completed

# Info

In [95]:
df=pd.read_csv("../data/raw.csv", header=[0, 1], index_col=0, parse_dates=True)
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 3770 entries, 2011-08-15 to 2026-08-12
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   (Close, SPY)   3770 non-null   float64
 1   (High, SPY)    3770 non-null   float64
 2   (Low, SPY)     3770 non-null   float64
 3   (Open, SPY)    3770 non-null   float64
 4   (Volume, SPY)  3770 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 176.7 KB

In [96]:
df.head()

Price           Close       High        Low       Open     Volume
Ticker            SPY        SPY        SPY        SPY        SPY
Date
2011-08-15  92.641960  92.734122  91.397720  91.543651  258810600
2011-08-16  91.850838  92.695695  90.867737  91.758676  294095200
2011-08-17  91.912300  93.087413  91.182657  92.357769  238201100
2011-08-18  87.949150  91.942996  87.088934  89.477563  512956300
2011-08-19  86.512871  89.001343  86.405345  86.758646  428281300

In [97]:
df.tail()

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2026-08-06  768.559998  771.820007  767.460022  770.210022  38416900
2026-08-07  773.260010  773.919983  769.609985  771.020020  43586300
2026-08-10  773.030029  775.049988  771.619995  772.599976  39249500
2026-08-11  770.559998  774.609985  769.200012  774.530029  36740600
2026-08-12  772.489990  774.900024  771.280029  774.710022  33179100

In [98]:
df.describe()

Price         Close         High          Low         Open        Volume
Ticker          SPY          SPY          SPY          SPY           SPY
count   3770.000000  3770.000000  3770.000000  3770.000000  3.770000e+03
mean     304.377455   305.934993   302.560198   304.317256  9.742406e+07
std      170.289119   171.106706   169.309238   170.258663  5.412523e+07
min       84.868332    86.914179    82.938267    83.648525  2.027000e+07
25%      169.691990   170.335698   168.654176   169.554573  6.235858e+07
50%      250.860497   252.141787   249.469031   250.969256  8.293200e+07
75%      410.382019   412.374068   407.164099   409.863941  1.155060e+08
max      773.260010   776.849976   771.619995   775.849976  5.139113e+08

In [99]:
date_gaps=df.index.to_series().diff()
date_gaps.sort_values(ascending=False).head(10)

Date
2012-10-31   5 days
2022-04-18   4 days
2021-07-06   4 days
2014-02-18   4 days
2013-05-28   4 days
2024-02-20   4 days
2016-01-19   4 days
2012-05-29   4 days
2015-09-08   4 days
2019-01-22   4 days
Name: Date, dtype: timedelta64[us]

In [100]:
df.index.duplicated().sum()

np.int64(0)

In [101]:
(df["Volume"] == 0).sum()

Ticker
SPY    0
dtype: int64

# Data Cleaning

Fixing Multi Indexing

In [102]:
df.columns = df.columns.get_level_values(0)
df.columns.name = None
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 3770 entries, 2011-08-15 to 2026-08-12
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   3770 non-null   float64
 1   High    3770 non-null   float64
 2   Low     3770 non-null   float64
 3   Open    3770 non-null   float64
 4   Volume  3770 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 176.7 KB

In [103]:
df.isnull().sum()

Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [104]:
df.duplicated().sum()

np.int64(0)

In [105]:
df = df.sort_index()
df.index.is_monotonic_increasing

True

In [106]:
df.dtypes

Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

No missing/duplicate values found So no need for imputation.

In [107]:
df.to_csv("../data/processed.csv")